### ISSUE TITLE
Not a real issue: Video links broken

### ISSUE THREAD

**Issue by anshul360** [karpathy/nn-zero-to-hero#14]
youtube video links for lectures 3, 4, 5 are broken..not sure if its just me facing the issue

**Comment by masslightsquared** [comment]
I tested the links for lectures 3, 4, and 5, and they're working for me. Have you tried clearing your cache, or perhaps testing the links on an alternate browser?

**Comment by JonathanSum** [comment]
I tested the link on https://github.com/karpathy/nn-zero-to-hero. The youtube links are fine.

**Comment by anshul360** [comment]
@masslightsquared @JonathanSum It seems like the links will not work on any device which does not have Youtube app installed. I am using a windows machine and links not working on it (tried chrome, firefox, edge). Although I am able to open links on my android phone.

**Comment by JonathanSum** [comment]
@anshul360 
I am using a Windows 11 on chrome with the link is [this youtube link](https://www.youtube.com/watch?v=VMj-3S1tku0) .

**Comment by anshul360** [comment]
closing the issue. looks like this issue is specific to my machine.
