### ISSUE TITLE
intro to neural networks first

### ISSUE THREAD

**Issue by culurciello** [karpathy/nn-zero-to-hero#15]
Hi Andrej, this is really great and thank you so very much for the material. It is truly super useful!

I wonder, what would you use before this series, to introduce neural nets, what they do / can do, the foundation before diving into back-prop?

Have you seen a nice lecture that does that in a simple way, just aligned with your course and material?

**Comment by B8ni** [comment]
I can suggest to see FastAI lecture 3: https://course.fast.ai/Lessons/lesson3.html

**Comment by B8ni** [comment]
It's a pleasure prof!
