### ISSUE TITLE
Discrepancy in makemore_part1_bigrams single sample draw

### ISSUE THREAD

**Issue by anoopelias** [karpathy/nn-zero-to-hero#34]
When I run the makemore_part1_bigrams notebook, in the cell where we draw a single sample based on probability distribution in the _first row_ of `N`, I get a different sample ( 'c' ) compared to the one in the video ( 'm' ). Everything else until then seems to be the same, with manually seeded generator, I'd expect even this to match exactly.

Value in this repo (and the video):
<img width="984" alt="image" src="https://user-images.githubusercontent.com/798009/231938240-53c8f302-ee46-4b61-9760-59eabd6492ef.png">

My run:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/798009/231937717-2bb7a73a-2f1f-4db1-8880-91a9407207cf.png">

I have pushed the full run until this cell in the commit [here](https://github.com/anoopelias/nn-zero-to-hero/commit/6b351033073d30cc9b7a40b1a4674f8126c94c69#diff-b937978dd6a29f51a8d78918b9418a9bc715bb0cac7d449cab608b8e98602d45L892).

What am I missing?

**Comment by ratelle** [comment]
This seems to be bug in pytorch 2.0.0 when calling multinomial with num_samples=1. If you run the same code using pytorch 1.13.1, you will get the correct result.

**Comment by anoopelias** [comment]
Thank you! This solves the problem. Thread to the original discussion [here](https://discuss.pytorch.org/t/odd-result-using-multinomial-num-samples-1-vs-larger-sizes/175231).
