### ISSUE TITLE
Bug on `lectures/micrograd/micrograd_lecture_second_half_roughly.ipynb`

### ISSUE THREAD

**Issue by younes-io** [karpathy/nn-zero-to-hero#52]
First of all, thank you @karpathy for this amazing repo.

I think the `exp` function in the [second half of the first lecture of micrograd](https://github.com/karpathy/nn-zero-to-hero/blob/master/lectures/micrograd/micrograd_lecture_second_half_roughly.ipynb) has a bug:

```python
def exp(self):
    x = self.data
    out = Value(math.exp(x), (self, ), 'exp')
    
    def _backward():
      self.grad += out.data * out.grad # NOTE: in the video I incorrectly used = instead of +=. Fixed here.
    out._backward = _backward
    
    return out
```

The gradient should be calculated like this: `self.grad += self.data * out.grad` 

What do you think?

**Comment by haduoken** [comment]
local grad is exp(x), so we use out.data, not self.data @younes-io
